# Generated by Django 5.1.7 on 2025-04-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusmart', '0002_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
